image: docker

services:
  - docker:dind

before_script:
    - apk add --no-cache docker-compose
    - touch .env
    - echo 'POSTGRES_HOST=durofrio_db' >> .env
    - echo 'POSTGRES_DB=durofrio' >> .env
    - echo 'POSTGRES_USER=durofrio' >> .env
    - echo 'POSTGRES_PASSWORD=durofrio_password' >> .env
    - echo 'POSTGRES_PORT=5432' >> .env
    - echo 'DJANGO_SETTINGS_MODULE=durofrio.settings.development' >> .env
    - echo 'SECRET_KEY=NON_SECRET' >> .env
    - echo 'ALLOWED_HOSTS=*' >> .env
    - echo 'DEBUG=True' >> .env

build:
  stage: build
  script:
    - docker-compose build

test:
  stage: test
  script:
    - docker-compose up -d
    - docker-compose run durofrio_web python manage.py test --parallel
    - docker image list
    - docker ps
